apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "client-test-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "client-test-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "client-test-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "client-test-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "client-test-helm.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mock-agent # the mock Agent(alpine) to echo the config files
          image: alpine
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args: [ "-c", "apk update && apk add inotify-tools && while true; do inotifywait -e modify $CONFIG_FILE_PATH/$CONFIG_FILE_NAME; cat  $CONFIG_FILE_PATH/$CONFIG_FILE_NAME; done" ]
          envFrom:
            - configMapRef:
                name: {{ include "client-test-helm.fullname" . }}
          volumeMounts:
            - name: fso-agent-management-client-data
              mountPath: {{ .Values.config.file.path }}
        - name: fso-agent-management-client
          # using the agent-config-client image which is designed to write the configs received directly to
          # a file, which will help us to see the deployment objects received to the Orchestration client
          # just by changes CLIENT_TYPE we should be able to check both Orchestration client and
          # agent-config-client chases
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: INSTANCE_UID
              value: INSTANCE_UID_VALUE
            - name: CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace # defaults to appdynamics
            - name: INSTALLED_TIME
              value: "INSTALLED_TIME_VALUE"
            - name: CLUSTER_ID
              value: "CLUSTER_ID_VALUE"
            - name: K8_OBJECT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          envFrom:
            - configMapRef:
                name: {{ include "client-test-helm.fullname" . }}
            - secretRef:
                name: {{ include "client-test-helm.fullname" . }}-new
          volumeMounts:
            - name: fso-agent-management-client-data
              mountPath: {{ .Values.config.file.path }}
      volumes:
        - name: fso-agent-management-client-data
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
