apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "client-test-helm.fullname" . }}-new
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "client-test-helm.labels" . | nindent 4 }}-new
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - deployments/status
      - replicasets
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/logs
      - pods/status
    verbs:
      - create
      - delete
      - get
      - list
      - watch
      - update
      - patch