apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "client-test-helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "client-test-helm.labels" . | nindent 4 }}
  annotations:
    {{- toYaml . | nindent 4 }}
